# Spring Application Name
spring.application.name=bib-flip-backend

# Default Spring Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:azure}

# Mail Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_EMITTER}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.from=${EMAIL_EMITTER}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# JWT Configuration
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=7

# Time Zone Configuration (Will be descommented in future sprint to use America/Lima timezone)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jackson.time-zone=America/Lima